---
title: "Survival Analysis On Lung Cancer Dataset"
author: "Daniel Mon"
date: "2024-12-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library(knitr)
library(dplyr)
library(survival)
library(ggplot2)
library(tibble)
library(lubridate)
library(ggsurvfit)
library(gtsummary)
library(tidycmprsk)
library(devtools)
devtools::install_github("zabore/condsurv")
library(condsurv)
devtools::install_github("zabore/ezfun")
library(ezfun)
ezfun::set_ccf_palette("contrast")

```
```{r}
lung_cancer_df<-lung
lung_cancer_df
```

```{r}
lung_cancer_df
lung_cancer_df<-lung_cancer_df%>%mutate(
    status = recode(status, `1` = 0, `2` = 1)
  )
lung_cancer_df
```
```{r}
head(lung_cancer_df[, c("time", "status", "sex")])
```

```{r}
Surv(lung_cancer_df$time, lung_cancer_df$status)[1:10]
```

```{r}
s1 <- survfit(Surv(time, status) ~ 1, data = lung_cancer_df)
str(s1)
```
```{r}
survfit2(Surv(time, status) ~ 1, data = lung_cancer_df) %>% 
  ggsurvfit() +
  labs(
    x = "Days",
    y = "Overall survival probability"
  )
```
```{r}
survfit2(Surv(time, status) ~ 1, data = lung_cancer_df) %>% 
  ggsurvfit() +
  labs(
    x = "Days",
    y = "Overall survival probability"
  ) + 
  add_confidence_interval()
```

```{r}
survfit2(Surv(time, status) ~ 1, data = lung) %>% 
  ggsurvfit() +
  labs(
    x = "Days",
    y = "Overall survival probability"
    ) + 
  add_confidence_interval() +
  add_risktable()
```

```{r}
summary(survfit(Surv(time, status) ~ 1, data = lung_cancer_df), times = 365.25)
```

```{r}
survfit(Surv(time, status) ~ 1, data = lung_cancer_df) %>% 
  tbl_survfit(
    times = 365.25,
    label_header = "**1-year survival (95% CI)**"
  )
```

```{r}
lung_cancer_df %>% 
  filter(status == 1) %>% 
  summarize(median_surv = median(time))
```

```{r}
survfit(Surv(time, status) ~ 1, data = lung_cancer_df) %>% 
  tbl_survfit(
    probs = 0.5,
    label_header = "**Median survival (95% CI)**"
  )
```

```{r}
survdiff(Surv(time, status) ~ sex, data = lung_cancer_df)
```

```{r}
coxph(Surv(time, status) ~ sex, data = lung_cancer_df)
```

```{r}
coxph(Surv(time, status) ~ sex, data = lung_cancer_df) %>% 
  tbl_regression(exp = TRUE) 
```

